# topic
cloud_sub_topic: /velodyne_points
imu_sub_topic: /imu/data
gnss_sub_topic: /navsat/fix 

#sensor device
use_gnss: false



#calibration
calibration_matrix:
   lidar_to_imu: [-0.47342,  0.66084 ,-0.00000,-0.00000,
                                -0.66084, -0.47342 ,-0.00000 ,-0.00000,
                                -0.00000 , -0.00000,  1.00000,  0.28000,
                                -0.00000 , -0.00000, -0.00000,  1.00000]

  gnss_to_lidar: [ 1.00000, -0.00000,-0.00000,-0.00000,
                                -0.00000,  1.00000 ,-0.00000 ,-0.00000,
                               0.00000, -0.00000,  1.00000,  -0.00000,
                               0.00000,  -0.00000, -0.00000,  1.00000]



#registration
registration_method: NDT   

NDT:
  res : 1.0
  step_size : 0.1
  trans_eps : 0.01
  max_iter : 30

ICP:
  knn_num: 10
  max_iter: 20
  eps: 0.01


#filter
frames_filter: [1.3, 1.3, 1.3]
local_map_filter: [0.6, 0.6, 0.6]



# local map
local_map:
  key_frame_num: 20
  key_frame_distance: 0.5


#optimizer method
graph_optimizer: g2o #gtsam ceres handle

g2o_param:
    odom_noise: [0.1, 0.1, 0.1, 0.001, 0.001, 0.001] # noise y z yaw roll pitch
    close_loop_noise: [2.0, 2.0, 2.0, 0.01, 0.01, 0.01] # noise x y z yaw roll pitch
    gnss_noise: [2, 2, 2] # 噪声：x y z


#optimize step
key_frame_optimize_step: 10000  
gnss_optimize_step: 50 
close_loop_optimize_step: 100  



#result record
map_record_path: "resource/output"
