# 关键帧
data_path: ./   # 数据存放路径

# 关键帧
key_frame_distance: 2.0 # 关键帧距离

# 优化
graph_optimizer_type: g2o # 图优化库，目前支持g2o

use_gnss: true
use_close_loop: false

key_frame_optimize_step: 10000 # 没有其他信息时，每隔 step 发送一次优化的位姿
gnss_optimize_step: 50 # 每累计 step 个 gnss 观测时，优化一次
close_loop_optimize_step: 100  # 每累计 step 个闭环约束时优化一次

g2o_param:
    odom_noise: [0.1, 0.1, 0.1, 0.001, 0.001, 0.001] # 噪声：x y z yaw roll pitch
    close_loop_noise: [2.0, 2.0, 2.0, 0.01, 0.01, 0.01] # 噪声：x y z yaw roll pitch
    gnss_noise: [2, 2, 2] # 噪声：x y z
